// lib/ai/providers/MockProvider.ts
/**
 * Mock AI Provider for Testing and Fallback
 * Returns deterministic responses without calling external APIs
 */

import { AIProvider } from '../AIProvider'
import { AIGenerateRequest, AIResponse } from '../types'

export class MockProvider extends AIProvider {
  name: 'mock' = 'mock'
  displayName: string = 'Mock Provider (Testing)'

  private mockResponses: Map<string, string> = new Map()

  constructor() {
    super('mock-api-key')
    this.initializeDefaultResponses()
  }

  isConfigured(): boolean {
    return true // Mock is always available
  }

  /**
   * Initialize default mock responses
   */
  private initializeDefaultResponses(): void {
    // Add common mock responses
    this.mockResponses.set('hello', 'Hello! I\'m a mock AI assistant.')
    this.mockResponses.set('test', 'This is a test response from the mock AI provider.')
    this.mockResponses.set('json', JSON.stringify({ status: 'success', data: { test: true } }))
  }

  /**
   * Register custom mock response
   */
  registerMockResponse(prompt: string, response: string): void {
    this.mockResponses.set(prompt.toLowerCase(), response)
  }

  /**
   * Generate mock response
   */
  async generateText(request: AIGenerateRequest): Promise<AIResponse> {
    const requestId = `mock-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
    
    this.log('info', `Mock request: ${request.prompt.substring(0, 50)}...`)

    // Simulate processing delay
    await new Promise((resolve) => setTimeout(resolve, 100))

    // Find matching mock response
    const promptLower = request.prompt.toLowerCase()
    let response = null

    for (const [key, value] of this.mockResponses.entries()) {
      if (promptLower.includes(key)) {
        response = value
        break
      }
    }

    // Default response if no match
    if (!response) {
      response = this.generateDefaultResponse(request.prompt)
    }

    // Validate output
    await this.validateOutput(response)

    // Estimate tokens (1 token ≈ 4 characters)
    const inputTokens = Math.ceil(request.prompt.length / 4)
    const outputTokens = Math.ceil(response.length / 4)

    return {
      content: response,
      tokensUsed: {
        input: inputTokens,
        output: outputTokens,
        total: inputTokens + outputTokens,
      },
      model: 'mock-model',
      provider: this.name,
      timestamp: new Date(),
      requestId,
      finishReason: 'STOP',
    }
  }

  /**
   * Generate a reasonable default response
   */
  private generateDefaultResponse(prompt: string): string {
    // Detect request type
    if (prompt.includes('json') || prompt.includes('JSON')) {
      return JSON.stringify({
        status: 'success',
        data: {
          message: 'Mock JSON response',
          timestamp: new Date().toISOString(),
        },
      })
    }

    if (prompt.includes('summary') || prompt.includes('summarize')) {
      return 'This is a mock summary of the provided content. In a real scenario, the AI would analyze the input and provide a concise summary.'
    }

    if (prompt.includes('analyze')) {
      return 'Mock analysis:\n\n1. First point: This is a demonstration of the mock AI provider.\n2. Second point: It shows how responses will be formatted.\n3. Third point: In production, real AI would provide actual analysis.'
    }

    if (prompt.includes('generate') || prompt.includes('write')) {
      return 'Mock generated content: This is sample content generated by the mock AI provider. In production, this would be real content generated by the actual AI model.'
    }

    if (prompt.includes('list')) {
      return '1. First item\n2. Second item\n3. Third item\n4. Fourth item\n5. Fifth item'
    }

    if (prompt.includes('code') || prompt.includes('function')) {
      return `function mockFunction(input) {
  // This is mock code
  console.log('Processing:', input);
  return { status: 'success', result: input };
}`
    }

    // Generic response
    return `Mock AI Response: I received your request "${prompt.substring(0, 50)}..." and I'm responding in mock mode. This is a placeholder response from the MockProvider. In production, this would be an actual response from the Gemini API.`
  }

  /**
   * Count tokens (mock estimation)
   */
  async countTokens(text: string): Promise<number> {
    // Mock: 1 token ≈ 4 characters
    return Math.ceil(text.length / 4)
  }

  /**
   * Estimate cost (mock always returns 0)
   */
  estimateCost(tokens: number): number {
    return 0 // Mock provider is free
  }

  /**
   * Clear all mock responses
   */
  clearMockResponses(): void {
    this.mockResponses.clear()
    this.initializeDefaultResponses()
  }
}

/**
 * Local Rule-Based Provider
 * Uses deterministic rules instead of AI for simple decisions
 */
export class LocalRuleBasedProvider extends AIProvider {
  name: 'local' = 'local'
  displayName: string = 'Local Rule-Based Provider'

  constructor() {
    super()
  }

  isConfigured(): boolean {
    return true
  }

  /**
   * Process request using rules instead of AI
   */
  async generateText(request: AIGenerateRequest): Promise<AIResponse> {
    const requestId = `local-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
    
    this.log('info', `Local rule-based request: ${request.prompt.substring(0, 50)}...`)

    let response = ''

    // Apply rules based on prompt content
    const prompt = request.prompt.toLowerCase()

    // Email validation rule
    if (prompt.includes('email') && prompt.includes('valid')) {
      const emailRegex = /[^\s@]+@[^\s@]+\.[^\s@]+/
      response = emailRegex.test(prompt) ? 'Valid email format' : 'Invalid email format'
    }
    // Number extraction rule
    else if (prompt.includes('number') || prompt.includes('extract')) {
      const numbers = request.prompt.match(/\d+/g)
      response = numbers ? `Found numbers: ${numbers.join(', ')}` : 'No numbers found'
    }
    // Keyword detection rule
    else if (prompt.includes('keywords')) {
      const words = request.prompt.split(/\s+/).filter((w) => w.length > 4)
      response = `Keywords: ${words.slice(0, 5).join(', ')}`
    }
    // Count rule
    else if (prompt.includes('count')) {
      const words = request.prompt.split(/\s+/).length
      response = `Word count: ${words}`
    }
    // Default fallback
    else {
      response = 'Local rule-based processing: No matching rule for this request. Falling back to mock response.'
    }

    const inputTokens = Math.ceil(request.prompt.length / 4)
    const outputTokens = Math.ceil(response.length / 4)

    return {
      content: response,
      tokensUsed: {
        input: inputTokens,
        output: outputTokens,
        total: inputTokens + outputTokens,
      },
      model: 'local-rules',
      provider: this.name,
      timestamp: new Date(),
      requestId,
      finishReason: 'RULE_MATCHED',
    }
  }

  /**
   * Count tokens
   */
  async countTokens(text: string): Promise<number> {
    return Math.ceil(text.length / 4)
  }

  /**
   * Estimate cost
   */
  estimateCost(tokens: number): number {
    return 0 // Local processing is free
  }
}
